language: python
python:
  - "3.6"

services:
  - mongodb

install:
    - pip install -r tests/requirements.txt
    - pip install codecov

before_script:
    - sh meta/decompress.sh
    - python utils/add_pages.py --db_name=tripitaka_test
    - python utils/import_meta.py --db_name=tripitaka_test

script:
    - ./run_tests.py --cov=controller --cov-report=term tests

after_success:
    - codecov
